### ISSUE TITLE
Format the display of received money

### ISSUE THREAD

**Issue by gaam24** [Archy-X/AureliumSkills#11]
Once the level is reached, sometimes the money received displays with a lot of decimal places.
![124761298_1290602907941938_5918740630762954578_n](https://user-images.githubusercontent.com/23352901/98878399-2d0bdd00-2483-11eb-82ac-3df016f633ad.jpg)

**Comment by Archy-X** [comment]
Fixed in a commit, and will be fixed in the next update.
