### ISSUE TITLE
Bug with arrows

### ISSUE THREAD

**Issue by DimaSergeew** [Archy-X/AureliumSkills#110]
### Server software and version

 Aurelium Skills Beta 1.3.6 || Current: git-Purpur-1632

### Expected behavior

That this bug will be fixed in a short time as it carries a great danger

### Actual behavior

The error lies in the fact that the arrow starts to multiply infinitely, which breaks any server where this plugin is installed, my friend and I went to someone else's server with this plugin and accidentally caused a crash on it with this bug, that is, it works wherever this plugin is

### How to reproduce

The error works as follows, it is quite difficult to repeat since it requires pumped skills, Player A and Player B, Player A takes the shield and looks up with the shield, player B stands on top and shoots player A exactly in the head from the top, the arrow starts to jump on shield and breaks its mechanics, it starts to multiply very quickly and infinitely in quantity, that is, 2 + 2 = 4 + 4 = 16 + 16 = 32 + 32 = 64 and this happens very quickly, because of which the tps server starts to fall very quickly and the server crashes, this bug disappears if you disable the Aurelium Skills plugin, so there is reason to believe that this is a problem in it.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This will be fixed in the next update. In the meantime you can disable the Piercing Archery ability to prevent it from happening.

**Comment by Archy-X** [comment]
In abilities_config.yml under abilities.archery.piercing.enabled

**Comment by DimaSergeew** [comment]
> In abilities_config.yml under abilities.archery.piercing.enabled

When the fix comes out, I've been waiting for it for a long time
