### ISSUE TITLE
Mana Overflows wisdom becomes lower

### ISSUE THREAD

**Issue by ZenoCoding** [Archy-X/AureliumSkills#116]
### Server software and version

Paper 1.19.1

### Expected behavior

When obtaining a temporary buff of wisdom, your maximum mana is increased, allowing your mana to go past that point. If that wisdom/mana is removed, then the mana exceeding the maximum mana should be removed as well.

### Actual behavior

Mana behaves normally upon gaining wisdom, but doesn't reset when losing it.
Mana generates to temporary maximum (whilst holding item)
<img width="342" alt="Screen Shot 2022-08-07 at 1 34 19 AM" src="https://user-images.githubusercontent.com/51522505/183282429-62087fa0-ec8e-42dc-a58d-4c5c97100577.png">

Mana doesn't decrease upon unequipping the item, despite the maximum mana decreasing.
<img width="886" alt="Screen Shot 2022-08-07 at 1 34 59 AM" src="https://user-images.githubusercontent.com/51522505/183282453-2fa17f94-7717-4f3b-9413-4838330481e9.png">

### How to reproduce

Create a server with AureliumSkills on the latest version.
Apply a buff to your wisdom, and let your mana regenerate past your previous maximum mana.
Remove the buff, and your mana will not be decreased.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This is intended behavior. To disable it, set wisdom.allow-over-max-mana in the config to false.

**Comment by ZenoCoding** [comment]
Oh, ok thanks!
