### ISSUE TITLE
Health problem

### ISSUE THREAD

**Issue by DezApical** [Archy-X/AureliumSkills#120]
### Server software and version

Paper 1.18.2

### Expected behavior

Extra health is supposed to not decrease without getting damaged

### Actual behavior

If health is above 20, the player health will go back to 20 after some time. Max health don't change so you will regenerate, costing hunger.

### How to reproduce

1. Get extra max health from the Defense skill
2. Wait for a few seconds and the health will be set to 20

### Additional information

Plugins: ActionHealth, AdvancedBan, AdvancedRegionMarket, AdvancedTeleport, ajLeaderboards, AnimatedScoreboard, AuctionHouse, AureliumSkills, BetterRTP, BetterTeams, BottledExp, ChestShop, ClearLag, CMILib, CustomEnchantments, DiscordSRV, EconomyShopGUI, Essentials, EssentialsChat, FarmingUpgrade, FarmProtect*, FastChunkPregenerator, GriefPrevention, GSit, HolographicDisplays, InsaneAnnouncer, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, ItemEdit, ItemTag, Jobs, LuckPerms, MoneyFromMobs, Multiverse-Core, MythicMobs, NoPlugins, PlaceholderAPI, PlayerKits, PluginConstructorAPI, ProtocolLib, Quests, ReviveMe, ServersNPC, SkinsRestorer, SmoothTimber, TabList, TDRPlaytime*, TerraformGenerator, Themis, TradeSystem, UltraRepair, UserLogin, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Resolved on Discord.
