### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [Archy-X/AureliumSkills#122]
### Feature description

Hello, I found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

### Additional context

AureliumSkills Version: Beta 1.3.7 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/Du1Y84K

Thanks.

**Comment by Archy-X** [comment]
Looks like the plugin is disabling, so it's normal for blocking operations to be on the main thread. You cannot create async threads when the plugin is disabling. All other save/load operations while the server is running are already done asynchronously, so the logs you sent seem like a nonissue.

**Comment by FunkyNico** [comment]
I understand, thank you for explaning this.
