### ISSUE TITLE
Fleeting Bonus Never Goes Away

### ISSUE THREAD

**Issue by cbarnet4** [Archy-X/AureliumSkills#14]
Sometimes when taking enough damage to get the fleeting bonus, the effect never goes away. This is reset-able by just doing /skills reload, but if a server restart is performed, the effect will persist through the restart, and can be stacked again with **another** fleeting bonus.

**Comment by Archy-X** [comment]
Can you be more specific on when Fleeting does not get removed? Or how to reproduce this bug?

**Comment by cbarnet4** [comment]
How I was able to reproduce the bug was using the custom-regen-mechanic rather than vanilla, then taking enough fall damage to get me in the fleeting bonus health requirement. Then when you regain enough health to have the bonus removed, it stays. /skills reload will reset your speed modifier to normal, but a server restart before doing /skills reload will leave the speed modifier on the player permanently upon restart. The player will be able to gain new fleeting bonuses and stack them. I still haven't been able to remove it from my player.

**Comment by Archy-X** [comment]
Should now be fixed
