### ISSUE TITLE
Only version 1.3.7 works

### ISSUE THREAD

**Issue by CyberFinn69** [Archy-X/AureliumSkills#141]
### Server software and version

Paper 1.19.2

### Expected behavior

For the plugin to load.

### Actual behavior

Only version 1.3.7 works. Any other version generates this error message:

<html>
<body>

218 | [12:06:33] [Server thread/ERROR]: Error occurred while enabling AureliumSkills vBeta 1.3.9 (Is it up to date?)
219 | java.lang.NoSuchFieldError: SYSTEM_CHAT
220 | at com.archyx.aureliumskills.ui.ActionBarCompatHandler.registerSystemChatListener(ActionBarCompatHandler.java:53) ~[AureliumSkills-Beta1.3.9.jar:?]
221 | at com.archyx.aureliumskills.ui.ActionBarCompatHandler.registerListeners(ActionBarCompatHandler.java:35) ~[AureliumSkills-Beta1.3.9.jar:?]
222 | at com.archyx.aureliumskills.AureliumSkills.onEnable(AureliumSkills.java:288) ~[AureliumSkills-Beta1.3.9.jar:?]
223 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
224 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
225 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
226 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-196]
227 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-196]
228 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-196]
229 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-196]
230 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-196]
231 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-196]
232 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-196]
233 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
234 | [12:06:33] [Server thread/INFO]: [AureliumSkills] Disabling AureliumSkills vBeta 1.3.9
235 | [12:06:33] [Server thread/ERROR]: Error occurred while disabling AureliumSkills vBeta 1.3.9 (Is it up to date?)
236 | java.lang.NullPointerException: Cannot invoke "com.archyx.aureliumskills.data.PlayerManager.getPlayerDataMap()" because "this.playerManager" is null
237 | at com.archyx.aureliumskills.AureliumSkills.onDisable(AureliumSkills.java:350) ~[AureliumSkills-Beta1.3.9.jar:?]
238 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
239 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
240 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
241 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
242 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
243 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-196]
244 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-196]
245 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-196]
246 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-196]
247 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-196]
248 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-196]
249 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-196]
250 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

</body>
</html>

### How to reproduce

I have no idea, but here are all the other plugins:

[12:17:05 INFO]: Plugins (47): AureliumSkills, BetterBees, BetterTridents, BigDoors, BigDoorsOpener, Bookshelf, ChestCleaner, ContainerPassthrough, CoreProtect, DamageIndicator, EasyCarts, EnhancedEnchants, Essentials, EssentialsChat, EssentialsGeoIP, FarmProtect*, FastCraft, FastLeafDecay, Genie, GeoFurnace, GSit, Hat, HorseTpWithMe, ImageMaps, InfinityMendingUnnerf, LevelledMobs, LuckPerms, MoarBows, NBTAPI, NoMobGriefing, Not-Too-Expensive, ParrotGlue, PetMaster, PiggyBack, PlaceholderAPI, PlaceItemsOnGroundRebuilt, ProtocolLib, RedstoneProximitySensor, ShulkerBoxBackPacks, SkinsRestorer, sleep-most, Tweakin, UnbreakableLeashes, Vault, VeinMiner, WirelessRedstone, WorldEdit

I'm running the server on Aternos.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by jurian112211** [comment]
I get this too, will try 1.3.7 now!

**Comment by jurian112211** [comment]
It works perfectly now, the only thing is that protocollib says this:
`[20:33:08 WARN]: [ProtocolLib] [PacketFilterManager] [AureliumSkills] Unsupported server packet in current Minecraft version: CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]`

**Comment by Archy-X** [comment]
To fix the issue, make sure you are running the latest ProtocolLib dev build: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by jurian112211** [comment]
I was already running that**😀**

**Comment by CyberFinn69** [comment]
Oh, I see, 1.19.2 requires de ProtocolLib dev builds. I can't install this on Aternos. Guess I'll just have to wait than. Thanks for answering tho!
