### ISSUE TITLE
Placeholders as offline player (--null in papi)

### ISSUE THREAD

**Issue by valeredev** [Archy-X/AureliumSkills#145]
### Feature description

I don't know if it's a bug or a feature.

When you use an aurelium placeholder with the --nullargument in papi (/papi parse --null %placeholders%), aurelium returns no value.

It should return a value.

Placeholders like %aureliumskills_lb_power_[place]_name% don't need an online player to work.

The result is that plugins like Citizen, on which you can set a name and a skin of an npc with a placeholder, can't use Aurelium placeholders.

An use case example, if you want to set an npc with the skin of the best Aurelium player, you can't.

More details on --null : https://www.spigotmc.org/resources/placeholderapi.6245/update?update=462869

**Comment by Archy-X** [comment]
This should be resolved as of Beta 1.3.11
