### ISSUE TITLE
Sugarcane fast leveling bug

### ISSUE THREAD

**Issue by GOLOKKU** [Archy-X/AureliumSkills#15]
you can fast leveling faster using sugarcane even without wait it grow
server info : Purpur-957     AureliumSkills version : alpha 1.6.3
config : default
how to reproduce bug : 

https://user-images.githubusercontent.com/49714008/105451275-d60a5b80-5cae-11eb-9413-8689af37f124.mp4

**Comment by Archy-X** [comment]
This should be fixed as of Alpha 1.6.4, re-open if it hasn't.
