### ISSUE TITLE
Crossbow bug

### ISSUE THREAD

**Issue by GOLOKKU** [Archy-X/AureliumSkills#16]
Crossbow leveling fighting skill instead of archery

Server version : git-Yatopia-12 (1.16.5)
Plugin : Alpha 1.6.4
How to reproduce bug :
use fireworks small ball explosion
shoot something

video :

https://user-images.githubusercontent.com/49714008/105975453-8d450f00-60c1-11eb-939d-96bd0a5ec1c9.mp4

also can you make github bug report tempelate too ?

**Comment by Archy-X** [comment]
This has been fixed.
