### ISSUE TITLE
The plugin has a bug!!

### ISSUE THREAD

**Issue by DimaSergeew** [Archy-X/AureliumSkills#160]
### Server software and version

PurPur 1.19.3

### Expected behavior

The problem is that in the plugin you can abuse experience on ores! For example, a player places an ore an ancient debris! and breaks it and puts it again and breaks it, and so it pumps its level to infinity !!!!

### Actual behavior

I think it's clear from the description

### How to reproduce

I think it's clear from the description

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Make sure you have check-block-replace set to true in config.yml

**Comment by Szabolcs2008** [comment]
I have the same issue on paper 1.19.2

**Comment by Archy-X** [comment]
Make sure you are on the latest version of the plugin, as it should be fixed there. You can reopen this if you still have the issue on latest.
