### ISSUE TITLE
Support for DecentHolograms as a provider of damage holograms

### ISSUE THREAD

**Issue by EagL3-GIT** [Archy-X/AureliumSkills#161]
### Feature description

Hello I would like to have a possiblity to use DecentHolograms as a damage holograms provider.
Currently there is only HolographicDIsplays, which is kinda junk.

### Additional context

Plugin: https://www.spigotmc.org/resources/decentholograms-1-8-1-19-3-papi-support-no-dependencies.96927/

**Comment by Archy-X** [comment]
This has been added since Beta 1.3.15
