### ISSUE TITLE
Archery xp based on damage broken?

### ISSUE THREAD

**Issue by CaioAquinorc** [Archy-X/AureliumSkills#167]
### Server software and version

1.19.3 paper

### Expected behavior

the function based on damage of the archery skill appears not to be working in the beta version 1.3.13 of AureliumSkills in version 1.19.3 paper server, it does not show error logs or anything like that it just does not work the player does not receive xp from the skill, it was installed correctly with the latest (devbuild protocollib)

### Actual behavior

player hits the target with the arrow and does not gain any archery experience

### How to reproduce

go to the main config of AureliumSkill set the function (damage-based) to true, start the server in version 1.19.3 paper to test shoot against any entity

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This is fixed in Beta 1.3.14
