### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Leymooo** [Archy-X/AureliumSkills#169]
### Server software and version

1.16.5

### Expected behavior

-

### Actual behavior

-

### How to reproduce

https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/data/storage/YamlStorageProvider.java#L222-L226

these checks ignore value of `removeFromMemory`, so if one of it will pass, PlayerData with `Player` object reference will never unloaded from memory if `removeFromMemory` is true(When player quits a server). Same for MySQL provider.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Leymooo** [comment]
but what if player data marked as `shouldNotSave`? 

https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/data/storage/YamlStorageProvider.java#L131-L132
https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/data/storage/YamlStorageProvider.java#L222
https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/data/storage/StorageProvider.java#L48


or what if a new player just joined server and leaves after a few seconds/minutes/etc?
https://github.com/Archy-X/AureliumSkills/blob/master/src/main/java/com/archyx/aureliumskills/data/storage/YamlStorageProvider.java#L224

**Comment by Archy-X** [comment]
Fixed in ca2ffa5dcea2b5d7b79691eb6bd3b067aff5410f
