### ISSUE TITLE
Using mana skill from shovel stops server

### ISSUE THREAD

**Issue by Bloodlex** [Archy-X/AureliumSkills#176]
### Server software and version

git-Purpur-1930 (MC: 1.19.3)*

### Expected behavior

Server should not stop.

### Actual behavior

**Pastebin:** [https://pastebin.com/Mb38DcD8](https://pastebin.com/Mb38DcD8)

### How to reproduce

Use right-click on a shovel and try to dig something.

### Additional information

Thank you for your help!

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
The Terraform mana ability is conflicting with the Tunnel enchant from ExcellentEnchants, since both break multiple blocks at the same time. You will have to disable one or the other to fix the issue. To disable Terraform, set mana_abilities.terraform.enabled to false in abilities_config.yml.

**Comment by Bloodlex** [comment]
> The Terraform mana ability is conflicting with the Tunnel enchant from ExcellentEnchants, since both break multiple blocks at the same time. You will have to disable one or the other to fix the issue. To disable Terraform, set mana_abilities.terraform.enabled to false in abilities_config.yml.

Okay, thank you very much - I'll do that 🙂.
