### ISSUE TITLE
Item modifier login bug

### ISSUE THREAD

**Issue by waiching514** [Archy-X/AureliumSkills#177]
### Server software and version

Paper 1.16.5

### Expected behavior

Item modifier login not checking hand

### Actual behavior

Item modifier login checking hand

### How to reproduce

player having a +50Health sword login and put that on chest, they will still keeping the +50Health stat 

### Additional information

![image](https://user-images.githubusercontent.com/29138111/233811703-1029e85b-ca24-499c-8d49-d8ee16f4dd54.png)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in d1e28fdf11faa0815e5593e7fd5c3ef48ebfa0be
