### ISSUE TITLE
Armour Modifier not removed after armour is removed

### ISSUE THREAD

**Issue by ZeusTheDev** [Archy-X/AureliumSkills#18]
**Server Version and Software**
Paper 1.16.4

**Description**
Armour Modifier not removed after armour is removed. In my case this was a helmet.

**How To Reproduce**
Steps to reproduce the behaviour:
1. us the /sk armor modifier add command to add a modifier to the helmet.
2. Equip the helmet.
3. Remove the helmet.

**Expected behaviour**
The stat specified in the modifier should increase when equipping the helmet and decrease after removing it.
**Actual behaviour**
The helmet increase the stat when equipped and does not decrease it when it is removed.

**Comment by Archy-X** [comment]
I cannot reproduce this issue, it could be a plugin incompatibility

**Comment by ZeusTheDev** [comment]
Alright, I'll do some more testing and see if I can figure out what's causing the issue.

**Comment by Archy-X** [comment]
Closing for now, reopen if you have more info
