### ISSUE TITLE
Gains from many farming xp sources are doubled

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#186]
### Server software and version

Beta 1.3.19

### Expected behavior

Farming xp gain is : xp gain set on sources_config.yml * the skill's xp gain multiplier (showed in xp sources menu)

### Actual behavior

The gained value for many farming sources is : (xp gain set on sources_config.yml * the skill's xp gain multiplier)*2 
So the gains are doubled.

Not doubled sources : 

- Sweet berries
- Glow berries
- Bamboos 
- Kelpt

Doubled sources : 

- All predefined others 
- Custom sources

### How to reproduce

1. reset farming levels
2. look the multiplied source value in xp sources menu
3. farm this resource and see

### Additional information

This bug has been aldready reported on github : https://github.com/Archy-X/AureliumSkills/issues/112 , and discord.
I hope this detailed Bug Report help you to fix that.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in f659a5a865c9e0ed4bd347a97b2b0202914a4a27
