### ISSUE TITLE
Player getting xp from hitting Armorstands

### ISSUE THREAD

**Issue by Err0rbns** [Archy-X/AureliumSkills#187]
### Server software and version

1.19.4

### Expected behavior

You should only get xp when killing mods or players with arent "respawnable".And  you should be able to set the xp you get from armorstands to 0.

### Actual behavior

When you hit an armor stand you get arround 30 xp per hit per armor stand and when you try to find it in the /skill - fighting - Xp Sources tab you cant find the armor stand there. I tried looking in the config file (sources_config.yml) and i oculdnt find nor create an option to disable xp from armor stand

### How to reproduce

Place many Armorstand in each other and hit them slowly best is to not have fireaspect on the sored but spweeping edge.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in f6387ce0bc5205b4eabe36b5b06ceaabd60097fd
