### ISSUE TITLE
Abilities and mana abilities "{current}→{next}" formats are not the same

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#189]
### Server software and version

Beta 1.3.19

### Expected behavior

Modify the format "{current} → {next}" in file "message_xx.yml", in menus.abilities.desc_upgrade_value, should modify the abilities and mana abilities printed textes.

### Actual behavior

Modify this format changes just the abilities textes, not the mana abilities textes.

### How to reproduce

1. Modify the format "{current} → {next}" in file "message_xx.yml", in menus.abilities.desc_upgrade_value
2. look an ability that is not max level and wich have a level scale value printed
3. look a mana ability that is not max level and wich have a level scale value printed
4. see the difference

### Additional information

Exemples, we have added some colors on the next value format. The first screen is an ability's description and the second one is a mana ability's description : 
![image](https://github.com/Archy-X/AureliumSkills/assets/104359902/48555f4c-1c2b-4f67-a748-fcc370db407c)
![image](https://github.com/Archy-X/AureliumSkills/assets/104359902/120c45cf-2374-4b75-adac-cd638e8b6f57)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in a5d1f435c31e63e09687dbe730c1a6122662ba9d
