### ISSUE TITLE
Custom Blocks is not a valid block!

### ISSUE THREAD

**Issue by LLIaMMaH** [Archy-X/AureliumSkills#19]
Добрый день. Добавил руды и кристаллы из модов для добычи в файл sources_config.yml. При загрузке выдаёт ошибку. Подскажите, как правильно прописать руды и кристаллы из модов?
sources:
  .....
  mining:
    stone: 0.2
    .......
    custom:
      thermal:tin_ore: 1.8
      thermal:copper_ore: 1.8
      mekanism:copper_ore: 1.8
Пробовал даже без указания модов, просто "copper_ore: 1.8", всё равно ошибка.
Ядро mohist-1.16.5-441-server.jar

Good day. Added ores and crystals from mining mods to sources_config.yml file. When loading, it gives an error. Tell me how to correctly register ores and crystals from mods?
sources:
   .....
   mining:
     stone: 0.2
     .......
     custom:
       thermal: tin_ore: 1.8
       thermal: copper_ore: 1.8
       mekanism: copper_ore: 1.8
Tried it even without specifying mods, just "copper_ore: 1.8", it's still an error.
Core mohist-1.16.5-441-server.jar

**Comment by Archy-X** [comment]
Modded blocks are not supported for xp sources and will likely never be, since Spigot and Paper are the only supported server types of this plugin.

**Comment by LLIaMMaH** [comment]
Очень жаль.
Very sorry.
