### ISSUE TITLE
exp dupe glitch.

### ISSUE THREAD

**Issue by Ecilpse** [Archy-X/AureliumSkills#196]
### Server software and version

1.19.2 purpur

### Expected behavior

player can dupe exp through grindstone.
Not all tools are like that, only certain tools, but I don't know the conditions.

### Actual behavior

any erros was not happend in console.
I attached a video that reproduces the bug below as a YouTube link.

### How to reproduce

youtube: https://youtu.be/D86m-QhIT6I

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Ecilpse** [comment]
[grindstone.zip](https://github.com/Archy-X/AureliumSkills/files/11583942/grindstone.zip)

i uploaded fawe schematic files that will help.
There's a grindstone and chest with a pick that's copied.

**Comment by Archy-X** [comment]
I need to know what keys/buttons were pressed to be able to reproduce this.

**Comment by Ecilpse** [comment]
> I need to know what keys/buttons were pressed to be able to reproduce this.

not key, just mouse button.

**Comment by Ecilpse** [comment]
and can you check discord ticket? i wrote 2 days ago, but not replied.

**Comment by Archy-X** [comment]
Found as an incompatibility with ItemsAdder on their side.
