### ISSUE TITLE
problem with armor requirement

### ISSUE THREAD

**Issue by miloszek2804** [Archy-X/AureliumSkills#197]
### Server software and version

Paper 1.19.2 lastest

### Expected behavior

I thought i can't wear armor if i don't fill requirement for it

### Actual behavior

I can wear the armor when i open my inventory and spam

### How to reproduce

Take armor
place on your head multiple times

### Additional information

[There](https://youtu.be/hc1PCr22pvk)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Answered on Discord, set modifier.armor.timer.enabled to true in config.yml.
