### ISSUE TITLE
Netherite dupe

### ISSUE THREAD

**Issue by Kheeto** [Archy-X/AureliumSkills#198]
### Server software and version

1.19.3

### Expected behavior

The mining skill gives you a change of getting multiple drops when mining ores. And this is working properly with ores such as diamonds, coals, or iron.

### Actual behavior

The issue occurs when mining ancient debris, because you still have a chance of getting multiple ores, this means you can mine one ancient debris and get 2, then place them back and repeat to get as much netherite as you want.
This doesn't happen when mining diamonds or other minerals because you don't get the ore block but only the item.

### How to reproduce

Give yourself some levels in the mining skill (like 20) and place a certain amount of ancient debris. Mine them with a pickaxe, and you will get back more ancient debris than you initially placed

### Additional information

[Video example](https://mega.nz/file/rW5iXSYb#5LuaO3uFLU5JA044l2ZbZGwAexAoPtILg4fFK69xT_8)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Make sure check-block-replace is set to true in config.yml and you are running the latest Aurelium Skills version (Beta 1.3.19).
