### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by Dkpita2** [Archy-X/AureliumSkills#2]
https://pastebin.com/cM2p3Kpm

PS: Every time that the server is restarted the player's statistics are restarted. I hope you can fix it soon, the plugin is 10/10

**Comment by Archy-X** [comment]
What action causes this error to occur?

**Comment by Dkpita2** [comment]
I have no idea, but every time that the server is restarted the player's statistics are restarted. When statistics are saved in data.yml the ones that have been improved are not saved with quotes, that may be the problem.

PS: I have a new issue https://pastebin.com/EfST1LJ0

**Comment by Dkpita2** [comment]
I have no idea, but every time that the server is restarted the player's statistics are restarted. When statistics are saved in data.yml the ones that have been improved are not saved with quotes, that may be the problem. 
I have done a test, I have leveled different skills, wait for the data to be saved and restart the server, this happened: 
https://pastebin.com/rBaSPs5y

PS: I have another issue (this happened the first time I loaded the plugin): https://pastebin.com/EfST1LJ0

**Comment by Dkpita2** [comment]
And the first failure I comment continues on this version: https://pastebin.com/swzVRi63
It occurs when I kill mobs

**Comment by Archy-X** [comment]
I haven't been able to replicate it. I'm using 1.16.1 paper on the latest plugin version and there are no errors when I kill mobs, Xp is applied like normal. Are there any errors in console on startup?

**Comment by Dkpita2** [comment]
I am using the latest version of Spigot 1.16.1. There is a console error at startup that I have previously linked.
This error came out when I loaded the plugin first time: https://pastebin.com/EfST1LJ0
And this error when trying to load data after a server reboot: https://pastebin.com/rBaSPs5y
(when this error occurs the skills are reset)

**Comment by Archy-X** [comment]
Delete RECORD_WAIT (or something similar) from loot.yml, it should fix it that error. As for the skill loading error, that has to do with your locale formatting decimals with a "," instead of a ".". I will fix this in the next update.

**Comment by Archy-X** [comment]
The update that contains the skill loading/saving fix has been released. Verify if the bug is fixed, if so close the issue.

**Comment by Dkpita2** [comment]
I have tested it and now it works perfectly, for now I have not got any errors. If I discover any kind of error, please report it, good job thanks ^^

PS: I am Spanish, could you add the spanish translation? pls, i have added it manually
