### ISSUE TITLE
Terraform bug (12 chunks), right clicking with offhand

### ISSUE THREAD

**Issue by octoshrimpy** [Archy-X/AureliumSkills#20]
**Server Version and Software**
e.g. Paper 1.16.5

**Description**
This problem is two-fold:

1. Right clicking to activate abilities overrides vanilla offhand mechanics; because of so, abilities are activated a lot more often than a player wants, when trying to break/place easily (pick in main, block in off)

2. Terraform ate somewhere around 10 to 12 chunk radius around me, all in the same layer, instead of default 4 blocks. I also have installed MineTinker but it shouldn't interfere with Skills' mechanics. 

**How To Reproduce**
1. right click with shovel at high level, and then dig. 

**Expected behavior**
As stated in wiki, 4 block radius max. 

**Actual behavior**
it destroys all blocks of similar hardness or lower in a _very large_ radius. Attached screenshot is only a smaller section I did for testing. It destroyed chests, dirt, grass (not all of it, oddly enough) flowers (not on top of the destroyed grass).

**Screenshots**
![image](https://user-images.githubusercontent.com/7097172/113373033-3230d200-9327-11eb-9124-3e98d22396b8.png)

---

**Thoughts** 
This mechanic was great in MCMMO when offhand did not exist. Since offhand is now a thing, the right click with a tool can no longer be assumed to be a "dead" action that leads nowhere. The plugin should check if the offhand is empty _or_ if player is sneaking. Adding these two `or` checks will allow for regular right clicking to still place blocks, torches or other offhand interactions without sacrificing accidentally triggering abilities.

**Comment by octoshrimpy** [comment]
I just realized I am on 1.6.5, updating to 1.6.7 and seeing if it persists.

**Comment by octoshrimpy** [comment]
Updated to 1.6.7, broke directly under me, and then flew up. you can see from the dirt "stains" where it broke, and it's bigger than the default radius, which I have not touched.
![image](https://user-images.githubusercontent.com/7097172/113374535-92754300-932a-11eb-8a50-c8b521e687e5.png)

**Comment by Archy-X** [comment]
The extra blocks broken is because AureliumSkills calls its own BlockBreakEvents for each block broken to make sure the player can actually break the block there. It probably is another plugin interfering but I can add a sort of cooldown to make sure that only one effective break happens.

As for the activation, I will fix this soon. Currently there is a require_sneak option for speed_mine in abilities_config.yml but it just outright requires sneak to activate. I'll probably do what you stated as the default, then add some options to configure it however you want.

**Comment by Archy-X** [comment]
I don't know how fast this will be fixed though, because the more changes I make in Alpha makes Beta development more tedious to update. I may have to put this in the Beta 1.0.0 update, which is mostly done but just needs one key feature to be finished.

**Comment by octoshrimpy** [comment]
Good call. I just remembered that Minetinkers has a 3x1 modifier for the spoon. That then becomes a multiplier for the blockbreak, since the player is the one "breaking" it. (reading the code). What about a hotfix patch within alpha?

**Comment by Archy-X** [comment]
I'll do a hotfix update tomorrow/today with what's currently in master plus these fixes.

**Comment by octoshrimpy** [comment]
sounds good! I got started on a patch myself to PR, but you know the code much better. feel free to look over mine tho it has been a hot minute since I've done any Java haha

**Comment by Archy-X** [comment]
Sure I'll let you do what you can on the fixes and make any changes if necessary.

**Comment by octoshrimpy** [comment]
Done: https://github.com/Archy-X/AureliumSkills/pull/21

I did it in GH's web IDE, but it should be fine unless I misread or missed something.

**Comment by Archy-X** [comment]
I merged new options for when mana abilities should ready, but the too many blocks broken bug is going to have to wait because I don't know what that other plugin is doing to cause it, and there isn't an easy fix.

**Comment by octoshrimpy** [comment]
THe plugin is Minetinkers with the Power modifier, https://github.com/Flo56958/MineTinker/wiki/MineTinker-Explanation#power--axepickaxeshovel and that's just something that will always happen if those two are together, so no worries. now that I know about it, I can be more careful. :) Thank you for the quick fix!
