### ISSUE TITLE
Current mana exceeds max mana

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#206]
### Server software and version

Beta 1.3.21

### Expected behavior

The current ammount of mana can't exceeed the maximum amount of mana.

### Actual behavior

Sometimes, the current ammount of mana exceeeds the maximum amount of mana (no 1 or 2 points, sometimes it can be 20 or 40 points).

### How to reproduce

I have no idea where it can come from.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This is intended, you should set `wisdom.allow-over-max-mana` to false to prevent it.

**Comment by Pexep** [comment]
`wisdom.allow-over-max-mana` is already set to false.
