### ISSUE TITLE
Leveling Sorcery when she is blocked

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#207]
### Server software and version

Beta 1.3.21

### Expected behavior

When Sorcery is blocked, we shouldn't be able to earn xp in Sorcery.

### Actual behavior

When Sorcery is blocked, we can earn XP for Sorcery from mana abilities of other skills.

### How to reproduce

1. Set permission aureliumskills.sorcery to false (verify she's blocked clicking on Sorcery skill in skills menu)
2. Use mana abilities of other skills
3. See that you earn XP for Sorcery

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in da0db3227c8e44265604426742587909f25b5c6f
