### ISSUE TITLE
XP and multiplied XP display rounding are not the same

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#209]
### Server software and version

Beta 1.3.21

### Expected behavior

XP and multiplied XP display rounding should be the same.

### Actual behavior

XP and multiplied XP display rounding aren't the same.

### How to reproduce

1. Set a skill level  at 1
2. Delete all XP multipliers of this skill
3. Set the XP gain from a source of this skill at 0.04
4. Look the XP and multiplied XP in XP sources menu of this skill

### Additional information

"Gain" is the source XP gain and "Gain réel" is the source multiplied XP gain :
![image](https://github.com/Archy-X/AureliumSkills/assets/104359902/6619ae9e-71e1-42f8-ae65-4157f47e220f)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 1c450f3b0ae4fa5a9cb35633f28e5caccafae930
