### ISSUE TITLE
Bug with the XP sources menu size

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#210]
### Server software and version

Beta 1.3.21

### Expected behavior

When a page of an XP sources menu is full and there is not other sources to display, the item to go to the next page shouldn't be display.

### Actual behavior

When a page of an XP sources menu is full and there is not other sources to display, the item to go to the next page is display. Moreover, click on this item just close the menu.

### How to reproduce

1. Set enough XP sources of a skill at more than 0 (mining and fighting are good for this), to fill the first XP sources page of the skill
2. Look the first XP sources page of the skill and see that the item to go to the next page is display
3. Click on the item to go to the next page
4. The menu closes because there is no more page

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 558843fb7bf2184a1fdab1e04cebc8d22ddff686
