### ISSUE TITLE
Bleed is locked but affects ennemies

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AureliumSkills#214]
### Server software and version

Beta 1.3.21

### Expected behavior

When fighting ability "bleed" is locked, it shouldn't apply bleed on enemies.

### Actual behavior

When fighting ability "bleed" is locked, bleed can be applied on ennemies (with lvl.1 stats).

Also, but I'm not sure about that, the probability of bleed being applied seams higher than the actual probability (observed during playing). During tests, the observed probability was about 20% instead of 10% (but it's possibly by chance).

### How to reproduce

1. set the probability that bleed being applied to 100%
2. set the unlock level at 2
3. set all skills at 1
4. hit a mob and see

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 077c661302728d3085cbbba88ecb75b5f3a98787
