### ISSUE TITLE
Issue with Blocked Regions in Aurellium Skills Beta 1.3.2

### ISSUE THREAD

**Issue by DimaSergeew** [Archy-X/AureliumSkills#216]
### Server software and version

Minecraft 1.20.1

### Expected behavior

Players should be unable to level up their skills in specified blocked regions (e.g., "spawn").

### Actual behavior

Players can continue to level up their skills in blocked regions without any issues.

### How to reproduce

Set up Aurellium Skills Beta 1.3.21 on a server running Minecraft 1.20.1.
Specify "spawn" as a blocked region to prevent skill upgrades.
Observe that players can still upgrade their skills in the "spawn" region.

### Additional information

This issue began after the two most recent updates to the plugin. I kindly request you to investigate and address this issue.с

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
From what I see on DevBukkit and GitHub the latest version is 7.0.9 so that shouldn't be the issue. I just tested it too and was unable to reproduce the issue. What is your WorldGuard version?
