### ISSUE TITLE
Skills Sync

### ISSUE THREAD

**Issue by Yggdrasil80** [Archy-X/AureliumSkills#22]
**Server Version and Software**
Paper 1.16.5

**Description**
When i save my skills in the database, on my Spawn server, when im connect to my Construction server, the plugin don't find skills in the database to synchronise it.  So players, when changing server, have their skills reset

Can you add this option please in a future release ?

**Comment by Yggdrasil80** [comment]
Im trying to do that in my fork if someone wants to come ^^

**Comment by Archy-X** [comment]
This is coming in Beta, which you can already download pre-release builds for in the discord. Once you use beta, you just increase the mysql.load-delay

**Comment by Archy-X** [comment]
Beta has been fully released
