### ISSUE TITLE
PacketTooLarge error kick, requires server restart for kicked player to rejoin

### ISSUE THREAD

**Issue by micchu129** [Archy-X/AureliumSkills#223]
### Server software and version

Paper 196, MC version: 1.20.1, AureliumSkills Beta 1.3.23

### Expected behavior

Not getting kicked from server.

### Actual behavior

Getting kicked seemingly at random, sometimes on /skill command execution. 

example error in console: 
`[20:29:18] [Server thread/INFO]: _playername_ lost connection: Internal Exception: net.minecraft.network.PacketEncoder$PacketTooLargeException: PacketTooLarge - ClientboundLevelChunkWithLightPacket is 9976465. Max is 8388608`

Player receives the standard connection lost on their client

If they attempt to rejoin, both console and player client outputs similar error as above with slightly different Packet size value. 

### How to reproduce

Unsure what exactly causes kick. For some players it occurs after command executions.
For some it occurs during flight. 

### Additional information

I was trouble shooting random kicks in server, having uninstalled all plugins but the Nova framework.
Reinstalled AureliumSkills, LeveledMobs, and Spark and started receiving the packet too large error kicks.
Removed LeveledMobs, kick error persisted. Switched mobs and skills and kicks have not been happening.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by micchu129** [comment]
[2023-10-10-3.log](https://github.com/Archy-X/AureliumSkills/files/12872424/2023-10-10-3.log)

Here's my full log from yesterday's kick events.
Unfortunately I don't think it provides much more than the error message alone.

**Comment by Fly1337** [comment]
huh, I'd suggest using Plugman to unload the plugins one by one and see what happens. As you said, its sadly really not helpful which is pretty rare but still. I just doubt that AS is the fault.

**Comment by Archy-X** [comment]
It looks more like an issue with Paper or something in its configuration. I would make sure you're on the latest Paper and try increasing the max packet rate in the paper config.

**Comment by micchu129** [comment]
Thank you both for the assistance, I will keep troubleshooting other plugins and tweak the config.
It seems like one of my users was kicked again without AS installed so seems like it's definitely not an issue here
