### ISSUE TITLE
Make Charged Shot configurable or a command

### ISSUE THREAD

**Issue by Folas1337** [Archy-X/AureliumSkills#239]
### Feature description

I do not see the point in being able to toggle Charged Shots overall, I and other users on my server never disable it and only find it confusing when it's off without them noticing.
It would be awesome if the config had an option where you can disable it entirely or at the very least make it only toggleable through a command rather than left clicking with a bow.

### Additional context

While I'm at it, I noticed that the crossbow won't let you toggle the Charged Shot which is very confusing even though it's exactly the behavior I'd like to achieve with the bow from this feature request.

**Comment by Archy-X** [comment]
Added in f7ce1ee938952cf6479922ac9b11db132cd80406
