### ISSUE TITLE
Health Stays After Removing Plugin

### ISSUE THREAD

**Issue by NovaSoup** [Archy-X/AureliumSkills#25]
The title pretty much says it all. I installed Aurelium Skills on my Minehut server and I gave myself max stats to test it. Later, I removed it because the health unbalanced the server (I have custom mobs and a clear progression system I want people to follow). I replaced it with mcMMO (no offense lol). However, the health amount stayed, and now I can't test new features fairly because nobody else has the same huge amount of health as me.

**Comment by Archy-X** [comment]
See the bottom of this https://github.com/Archy-X/AureliumSkills/wiki/FAQ

**Comment by NovaSoup** [comment]
> See the bottom of this https://github.com/Archy-X/AureliumSkills/wiki/FAQ

Oops! Lol I looked at the beginning of the FAQ but somehow mist that. Thx!
