### ISSUE TITLE
Give XP With Command

### ISSUE THREAD

**Issue by DisguisedPixels** [Archy-X/AureliumSkills#26]
I believe that a command to give users xp (or remove) from a specific skill would be nice, especially for servers with custom mobs/bosses, and just jeneral maintenance without going to the config

Use: /aureliumskills:skillxp [give/set/remove] [player] [skill] [amount]

**Comment by fioxy** [comment]
This is already a feature in the plugin. Try doing 
/sk xp <add/set/remove> <player> <skill> <amount>
