### ISSUE TITLE
Mana bug

### ISSUE THREAD

**Issue by garsh1** [Archy-X/AureliumSkills#3]
Hello, I really like your plugin. One of the players on my server pointed out that mana isn't regenerating past 20 even when their capacity for mana is 24. I might have done something wrong but can you please help? Thanks.

**Comment by Archy-X** [comment]
This isn't a bug because there currently isn't any functionality for mana, I would recommend disabling mana on the action bar until I implement this system.

**Comment by garsh1** [comment]
Oh I see. Thanks for letting me know!
