### ISSUE TITLE
ru_RU

### ISSUE THREAD

**Issue by OstriySous-dev** [Archy-X/AureliumSkills#39]
**Server Version and Software**
PurPur 1.17

**Description**
no Russian lang by default

**Screenshots**
![image](https://user-images.githubusercontent.com/67519432/124663125-5c5bd800-deb2-11eb-930c-91a566682439.png)

please add ru here :)

**Comment by Archy-X** [comment]
That list doesn't update unless you regenerate your config file or use a new install, but you can still use it by setting default-language to ru or adding it to the list yourself.

**Comment by OstriySous-dev** [comment]
I deleted the plugin folder and nothing appeared. I also tried to enter it myself and for some reason it doesn't work (for others, too, it seems). Only the substitution of lang-en for lang-ru helped

**Comment by OstriySous-dev** [comment]
if anything I'm using the latest version

**Comment by Archy-X** [comment]
I see, I forgot to add it to the default config but you should still be able to add it yourself and have it work (make sure you restart the server though). If you only add it to the list you'll have to do /sk lang ru

**Comment by OstriySous-dev** [comment]
thx!
