### ISSUE TITLE
Cant cure health

### ISSUE THREAD

**Issue by Laxider** [Archy-X/AureliumSkills#40]
**Server Version and Software**
e.g. Spigot 1.17

**Description**
Even if the saturation is complete, it cannot be cured

**How To Reproduce**
1. Leveling "Farming" for more hearths

**Screenshots**
[https://imgur.com/a/9CtJtZy](url)

**Comment by Archy-X** [comment]
What other plugins are you using? This is likely a plugin compatibility issue.

**Comment by Laxider** [comment]
[INFO] Plugins (6): LuckPerms, AureliumSkills, ExtractableEnchantments, ServerEssentials, FancyBags, CustomEnchantments

**Comment by Archy-X** [comment]
Can you try removing the enchantment plugins one by one and see if it works again?

**Comment by Laxider** [comment]
Solution: Delete plugin CustomEnchants 
https://imgur.com/a/xOGIinn

**Comment by Archy-X** [comment]
Closing this but you should forward this issue to them to get it fixed
