### ISSUE TITLE
Don't skills doesn't gain

### ISSUE THREAD

**Issue by GraphIgor** [Archy-X/AureliumSkills#42]
**Server Version and Software**
e.g. Paper 1.17

**Description**
Doesn't work an Bossbar and skills, only show skills nothing more

**Expected behavior**

**Actual behavior**
Don't understand, but console sometimes going into red and stopping after some minutes

**Screenshots**
didn't

**Comment by Archy-X** [comment]
I don't understand what you mean, can you be more specific?
