### ISSUE TITLE
Inifitnite Stackoverflow error when installed with EcoEnchants then server cannot respond at all

### ISSUE THREAD

**Issue by Akiranya** [Archy-X/AureliumSkills#48]
**Server Version and Software**
Purpur 1.17.1

**Description**
Stackoveflow erros spamming on the console for more than ~ 14880000 lines.

**How To Reproduce**

I have no idea how to reproduce it sorry because it does not happen very often.

However, the server will not be able to respond at all if it happens.

One thing to be sure is that it has something to do with EcoEnchants...

I'll report it to the dev of EcoEnchants as well.

**Expected behavior**
Stackoverflow should not happen.

**Actual behavior**
Stackoverflow.

See: https://pastebin.ubuntu.com/p/fsXsyKKXxy/

**Screenshots**

**Comment by Archy-X** [comment]
Disable the Terraform mana ability in abilities_config.yml for now. A fix is coming in the next update.

**Comment by Akiranya** [comment]
Thanks for the so quick reply!!! I just reported the issue to the dev of EcoEnchants and the dev said this:

![image](https://user-images.githubusercontent.com/14846342/130102835-3e01698d-52ec-4564-8906-4de08679f103.png)

Just FYI :)

**Comment by Archy-X** [comment]
Yep someone already reported this, just need to release it (hopefully soon)

**Comment by Archy-X** [comment]
Fixed in Beta 1.2.1
