### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by Dkpita2** [Archy-X/AureliumSkills#5]
Hi again xD, I discovered another error and the reason why it occurs.
This is the error: https://pastebin.com/2x7Qk0u2
It happens when a NPC from Citizens plugin kills a mob

PS: Could you add the spanish translation? when you can, pls :)

**Comment by Archy-X** [comment]
Should be fixed in Alpha 1.2.0, let me know if it is fixed.

**Comment by Dkpita2** [comment]
It's fixed, nice work! 
I have discovered another bug, skills don't work with netherite tools

**Comment by Archy-X** [comment]
Issue closed, if netherite tools still don't work on version Alpha 1.3.0 or newer, make a new issue. However, I would join the discord where I respond faster to bugs. https://discord.gg/Bh2EZfB
