### ISSUE TITLE
Excessive Velocity Crash

### ISSUE THREAD

**Issue by Peeraboon** [Archy-X/AureliumSkills#53]
**Server Version and Software**
This server is running Paper version git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
AureliumSkills Beta 1.2.0

**Description**
The server crashed for some reason but i think it might related to AureliumSkills Fishing ability.

log: https://pastebin.com/VgL2xw8w

**How To Reproduce**
Don't know how

**Expected behavior**
-

**Actual behavior**
the server crashed

**Screenshots**
https://pastebin.com/VgL2xw8w

**Comment by Archy-X** [comment]
Try decreasing the abilities.fishing.grappler.per_level in abilities_config.yml. Also, what fishing level was the player who used the fishing tod at when this happened?

**Comment by Peeraboon** [comment]
I don't know who used the fishing rod at that time. 
And how much should i decrease? Currently, it is 100.

**Comment by Archy-X** [comment]
I would try 50 and see if it still happens or not
