### ISSUE TITLE
Compability issue with land protection plugins

### ISSUE THREAD

**Issue by Akiranya** [Archy-X/AureliumSkills#54]
**Server Version and Software**
Purpur 1.17.1

**Description**
Issue 1: If a player breaks a glowing berries which is within the WorldGuard region in which the player has no build permission, the player will still gain exp for corresponding skills (in this case, the player gains exp for farming .. ? can't exactly remember sorry) but the glowing berries is still there (because the player has no permission). As a result, the player could farming the exp by just keeping left-clicking the same glow berries all day.

Issue 2: If a player breaks the block (e.g. dirt) in the land of a town where he has no land permission, the player will gain exp corresponding to certain skill **and** the player will get extra drops triggered by skills **while** the block is still there. It's quite similar to the issue 1 where the player can just left-click all day to gain skill exp and also drops.

I believe this might imply that there are also compability issues with other land protection plugins, due to the fact of how the land proection plugins set the cancel states of some BlockBreakEvent and how AureliumSkills check the cancel states of the event with some handler priority.

This is just my reasoning of how this problem can happen. Sorry if it's wrong 🍡 

**How To Reproduce**
Create a protected area with WorldGuard
As a normal player without moderator permission
Breaks some glowing berries within the protected area
Exp gains while the glowing berries is still there

**Expected behavior**
If the player has no permission of the protected area, such actions should not gain player exp.

**Actual behavior**
Exp gains but the block is still there.

**Screenshots**

**Comment by Archy-X** [comment]
I am unable to produce this issue, region protections work fine. Check to make sure you have the check-cancelled options for each skill in config.yml set to true. If that doesn't work, it might be another plugin causing an incompatibility.

**Comment by Akiranya** [comment]
That's weird .. I'll look into the issue further ..

**Comment by Folas1337** [comment]
I can confirm this exact behaviour with the check on using Towny as a protection.
I wasn't able to reproduce it with GriefPrevention though so they have to be doing something differently somehow but I can unfortunately not tell you what.

I'd appreciate another look into this :)

**Comment by Folas1337** [comment]
This is quite a game breaking bug, a response would really be appreciated :)

**Comment by Archy-X** [comment]
Just tested on 1.18.1 using TownyAdvanced and WorldGuard and was still unable to reproduce. XP wasn't given for glow berries or breaking dirt in the protected region. Did you change any options in any plugins (including Aurelium Skills) that might affect this?

**Comment by Archy-X** [comment]
Ok, finally was able to reproduce it and the fix was just putting Towny into the soft-depend for Aurelium Skills. There was Towny support that originally fixed this issue but somehow the soft-depend was overlooked, causing the fix to not activate sometimes.
