### ISSUE TITLE
add info to wiki about modifier item NBT tags

### ISSUE THREAD

**Issue by raulsammelselg** [Archy-X/AureliumSkills#58]
**Feature Description**
Add info about modifier NBT tags

**Additional context**
I currently found myself looking for info how to add the stat modifiers to an item through /give command and I couldn't find any info about it. I am currently using the server plugin and would like to have a custom item given to a player with a stat modifier already applied.

**Comment by Archy-X** [comment]
I've added it here: https://wiki.aurelium.dev/skills/gameplay/stats/stat-modifiers#nbt-tags
