### ISSUE TITLE
Item/Armour modifiers retain after player re-logins to server even if taking off afterwards

### ISSUE THREAD

**Issue by Akiranya** [Archy-X/AureliumSkills#59]
**Server Version and Software**
Purpur 1.17.1

**Description**
Idealy, the item/armour modifiers should disappear when the player takes off the armour or unhold the item. It works well during the same session of the player but it does not if the player logs out and in. See repo steps for details. 

**How To Reproduce**
1. put on the armour with stats modifiers
2. log out the server
3. log in back
4. take off the armour
5. stats modifiers still remain

**Expected behavior**
The item/armour modifiers should be removed from the player when the player takes off the armour or unholds the item even though the player logged out and in.

**Actual behavior**
See repo steps, the stats modifiers still remain after such log in and out operation.
FYI, the stats modifers will retain forever as long as the player doesn't put on and hold something with stats modifiers later on.

**Screenshots**

**Comment by Archy-X** [comment]
I could not reproduce this issue on the latest version of Paper 1.17.1.

**Comment by Akiranya** [comment]
Hmm I cant repoduce it neither. Probably it was other plugin interfering it. I'll let you know if this happens again
