### ISSUE TITLE
Get multiple level at same time

### ISSUE THREAD

**Issue by Elikill58** [Archy-X/AureliumSkills#6]
Hi, to test, I edit XP and I set stone to 1000xp.
The problem is that It spam of message because I win a lot of level.
Can you compile all level obtains in one just visually ?

**Comment by Archy-X** [comment]
If you are gaining lots of levels fast, then just decrease the xp gained from sources or increase the level requirement. This isn't necessary as most of the time you aren't going to be gaining thousands of xp with one action.
