### ISSUE TITLE
Disabled skill inconsistency between stat and skill menus

### ISSUE THREAD

**Issue by zsturgess** [Archy-X/AureliumSkills#66]
### Server software and version

Paper 1.17.1

### Expected behavior

When a skill is disabled in config.yml, the skill is removed from all menus

### Actual behavior

A disabled skill is only removed from the skills menu.
The stats menu will continue to reference the disabled skill until the stats are taken out of the disabled skill's rewards.

### How to reproduce

1. Install AureliumSkills
2. Disable any skill by setting `enabled: false` in `plugins/AureliumSkills/config.yml`
3. Observe the skill is missing from `/sk` menu, but is still referenced in the `/stats` menu

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 173ba9d253, will be in next update
