### ISSUE TITLE
Armor Modifier Not Working if Armor is Automatically Equipped to Player

### ISSUE THREAD

**Issue by michaelr1300** [Archy-X/AureliumSkills#67]
### Server software and version

git-Purpur-1419 (MC: 1.17.1)

### Expected behavior

Armor modifier should instantly add points to player's `/stats`

### Actual behavior

- Armor modifier does not add points to player's `/stats`
- Player has to rejoin the server / re-equip the armor to get the modifier

### How to reproduce

1. Get a plugin that can auto equip armor to player (e.g. PlayerKits)
2. Create a kit containing armor with Aurelium modifier
3. Give the kit to player

### Additional information

Note: Equipping armor manually works normal, it still add modifier to player `/stats

https://user-images.githubusercontent.com/46708593/139541741-99da1339-b2ef-4d78-82f2-3e23a1cda551.mp4

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Try setting modifier.armor.timer.enabled to true in config.yml, it should fix it.

**Comment by michaelr1300** [comment]
> Try setting modifier.armor.timer.enabled to true in config.yml, it should fix it.

Ahh yes, that got it fix. Didn't see that option, my bad
