### ISSUE TITLE
bug o not 

### ISSUE THREAD

**Issue by dinobossytnew** [Archy-X/AureliumSkills#68]
### Server software and version

paper 1.16.5

### Expected behavior

https://www.toptal.com/developers/hastebin/juwuwilumu.yaml

### Actual behavior

not

### How to reproduce

bro I can only tell you what the user who used it told me,

when he was killing a mob his mana was deducted and pos crasho a null entity#getvehicles I don't have a vehicles plugin so no idea. 

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This does not seem related to Aurelium Skills at all.
