### ISSUE TITLE
Slimefun Mining Dupe

### ISSUE THREAD

**Issue by Primqd** [Archy-X/AureliumSkills#69]
### Server software and version

Paper 1.17.1

### Expected behavior

I could mine the Ancient Debris spawned by the Slimefun Block Placer without gaining mining exp, as well as having the Lucky Miner perk not activate.

### Actual behavior

I got mining exp from mining the Ancient Debris spawned by the Slimefun Block Placer, as well as duping the Ancient Debris occassionally..

### How to reproduce

1. Spawn a Slimefun Block Placer.
2. Place it down.
3. Put Ancient Debris into it's inventory.
4. Power it.
5. Mine the Ancient Debris that spawns.
6. You should get the mining exp that Ancient Debris gives, as well as occasionally duping it due to Lucky Miner.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Icyscools** [comment]
Hey, @Archy-X  
I can reproduce the bug like the author said, also I tried to reproduce on the other blocks that can be used in the block placer of Slimefun. It reproduces the same bug. (etc. mining on the mineral block, harvesting on pumpkin and melon, foraging on the wooden log)

I have an idea to fix this with the [`BlockPlacerPlaceEvent`](https://github.com/Slimefun/Slimefun4/blob/558bfb5c37fa2983ccc1e06de1f35a0b005a80f5/src/main/java/io/github/thebusybiscuit/slimefun4/api/events/BlockPlacerPlaceEvent.java) in a Slimefun API. I can implement this for you if you want.

**Comment by Archy-X** [comment]
You are welcome to PR this change, but atm I don't have much time to work on Aurelium Skills so this is a low priority issue.
