### ISSUE TITLE
The drop from "2x drop ability" using tools with silk touch enchant

### ISSUE THREAD

**Issue by MrPolloo** [Archy-X/AureliumSkills#7]
When breaking block using tools with silk touch enchant, the double drop isn't work properly. Ex : Breaking stone with silk touch pickaxe, it will drop stone and cobblestone. Looks like it should drop stone because enchantment from the tools.

**Comment by Archy-X** [comment]
What other blocks have this issue other than cobblestone?

**Comment by Archy-X** [comment]
Should be fixed in the next update, reopen this issue if it is not completely fixed.

**Comment by MrPolloo** [comment]
gravel, clay, grass block, ore didn't have this bug.
