### ISSUE TITLE
Switching an Item with Item modifier/s while in your Main Hand Bug

### ISSUE THREAD

**Issue by YazeSan** [Archy-X/AureliumSkills#8]
When you put an item with item modifiers in your offhand while it is in your main hand,
then unequip it, and place it in your inventory without putting it in your main hand. The item modifiers still remains. (Still remains if it still in offhand)
Also, holding your item with item modifiers while it is in your main hand and then putting the item in your inventory or another slot also retains the item modifiers.
Both can be fixed by placing it in your main hand again but might be abused someday, something like stacking
item modifiers.
Let's say you have a sword with strength item modifier, an emerald with health item modifier, a steak with regen item modifier.
Doing those things above will let you have all these modifiers without changing slots. Though it doesn't seem to stack with the same stat modifier.

![bug item modifier](https://user-images.githubusercontent.com/74035553/98330126-ae531200-2034-11eb-9a39-ccabb48007a1.png)

**Comment by Archy-X** [comment]
What version is your server? Can you also send a video of the bug occurring? I can't seem to reproduce it on 1.12.2 and 1.16.4.

**Comment by YazeSan** [comment]
Using Paper 1.16.4 server, tried it again on a clean paper 1.16.4 server and the bug still works.
Here's the clip
https://youtu.be/GldULz99a-o

**Comment by Archy-X** [comment]
Fixed the issue, will be out in the next update.
