### ISSUE TITLE
After disabling the plugin players still can benefit for instance from higher health value

### ISSUE THREAD

**Issue by Bloodlex** [Archy-X/AureliumSkills#81]
### Server software and version

Purpur 1.17.1

### Expected behavior

I think that it should revert back to normal after disabling and then be restored after enabling. There could be also a command to do that without needing to remove plugin and restart server.

### Actual behavior

Players still can benefit from some things like extended health after removal of the plugin.

### How to reproduce

Enable the plugin, level some skills and then remove it. Players have for instance extended health although plugin is not running.

### Additional information

We would really appreciate that for our server, because we organize pvp events and would like to completely disable benefits from a plugin for a specific time. Would be really nice if we could that. Other than that plugin is just great, thank you 🙂 

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
To uninstall, you must put the plugin back and run skills resethealth in console when no players are online. Then, immediately remove the plugin and restart.

As for disabling without restarting, you can add a world to the disabled-worlds list in config.yml. This might not disable everything without a restart though.
