### ISSUE TITLE
ADD ALL TYPES OF BLOCKS FOR MINING SKILL

### ISSUE THREAD

**Issue by Ammorack** [Archy-X/AureliumSkills#83]
### Feature description

This page from source shows all  added blocks
[Link](https://github.com/Archy-X/AureliumSkills/blob/3a224217bb613a6fe23ad8563b2dab4a5fb4d847/src/main/java/com/archyx/aureliumskills/skills/mining/MiningSource.java)

There is missing blocks like IronBlock, CoalBlock, LapisLazuliBlock, DiamondBlock, etc.

It would be great, that you could add all mineable full size blocks.

**Comment by Archy-X** [comment]
This is already possible through custom block sources: https://wiki.aurelium.dev/skills/config/sources#custom-blocks
