### ISSUE TITLE
Null messages in console when a npc kills or got hit by an entity/player

### ISSUE THREAD

**Issue by YazeSan** [Archy-X/AureliumSkills#9]
I am using the latest version of Aurelium Skills and Citizens Sentinels
This happens when a npc gets hit by an entity or player
Error1: https://pastebin.com/v4bY2wdk
This happens when a npc kills another entity or player
Error2: https://pastebin.com/qB4fZFjj

**Comment by Archy-X** [comment]
Fixed in a commit, will be fixed in the next update.
