### ISSUE TITLE
alchemy and excavation placeholder not working

### ISSUE THREAD

**Issue by NightLife-SG** [Archy-X/AureliumSkills#95]
### Server software and version

paper 1.18.1

### Expected behavior

im using placeholder to display level and rank

but two of them is not working,it doesnt display out the number

### Actual behavior

no rank or skill level is displayed when using the placeholder

### How to reproduce

![discord](https://user-images.githubusercontent.com/84533050/159148591-fffa34d0-b5a2-4e65-b122-7173b8135e0f.png)
`level: %aureliumskills_excavation%aureliumskills_rank_excavation%

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
The end of the first placeholder should have another % to close it properly.
