### ISSUE TITLE
fleeting skill does not take `health_percent_required` into account in french translation

### ISSUE THREAD

**Issue by iwa** [Archy-X/AureliumSkills#98]
### Server software and version

Paper 1.18.2 (287)

### Expected behavior

the fleeting skill config should show the percentage needed accordingly to the config

### Actual behavior

it does not take any value and stick to "less than 20% health"

### How to reproduce

- install the plugin
- put the plugin in french
- try to edit the `health_percent_required` value
- reload and/or restart
- see how it sticks to the 20% value in the skill description

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Since the percentage text is static in all translations, you will have to go into the messages_fr.yml and edit the abilities.fleeting.desc message and change 20% to your percentage.

**Comment by iwa** [comment]
ah okey, didn't know about that
thanks for the reply!
